# coding: utf-8

"""
    ConsumerDataStandards_Digital_Regulatory

    The product \\amp Product Details APIs allow third-parties to retrieve a list of Product categories \\amp details for Citi and our White-label Partners.  # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: cdr-data61@csiro.au
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.links_paginated import LinksPaginated  # noqa: E501
from swagger_client.rest import ApiException


class TestLinksPaginated(unittest.TestCase):
    """LinksPaginated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinksPaginated(self):
        """Test LinksPaginated"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.links_paginated.LinksPaginated()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
