# coding: utf-8

"""
ConsumerDataStandards_Digital_Regulatory

The product \\amp Product Details APIs allow third-parties to retrieve a list of Product categories \\amp details for Citi and our White-label Partners.  # noqa: E501

OpenAPI spec version: 1.2.0
Contact: cdr-data61@csiro.au
Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.banking_api import BankingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBankingApi(unittest.TestCase):
    """BankingApi unit test stubs"""

    def setUp(self):
        self.api = BankingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_product_detail(self):
        """Test case for get_product_detail

        Get Product Detail  # noqa: E501
        """
        pass

    def test_list_products(self):
        """Test case for list_products

        Get Products  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
