# coding: utf-8

"""
ConsumerDataStandards_Digital_Regulatory

The product \\amp Product Details APIs allow third-parties to retrieve a list of Product categories \\amp details for Citi and our White-label Partners.  # noqa: E501

OpenAPI spec version: 1.2.0
Contact: cdr-data61@csiro.au
Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.banking_product_category import (  # noqa: E501
    BankingProductCategory,
)
from swagger_client.rest import ApiException


class TestBankingProductCategory(unittest.TestCase):
    """BankingProductCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankingProductCategory(self):
        """Test BankingProductCategory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.banking_product_category.BankingProductCategory()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
