# coding: utf-8

"""
ConsumerDataStandards_Digital_Regulatory

The product \\amp Product Details APIs allow third-parties to retrieve a list of Product categories \\amp details for Citi and our White-label Partners.  # noqa: E501

OpenAPI spec version: 1.2.0
Contact: cdr-data61@csiro.au
Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.banking_product_v2_additional_information import (  # noqa: E501
    BankingProductV2AdditionalInformation,
)
from swagger_client.rest import ApiException


class TestBankingProductV2AdditionalInformation(unittest.TestCase):
    """BankingProductV2AdditionalInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankingProductV2AdditionalInformation(self):
        """Test BankingProductV2AdditionalInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.banking_product_v2_additional_information.BankingProductV2AdditionalInformation()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
