# coding: utf-8

"""
ConsumerDataStandards_Digital_Regulatory

The product \\amp Product Details APIs allow third-parties to retrieve a list of Product categories \\amp details for Citi and our White-label Partners.  # noqa: E501

OpenAPI spec version: 1.2.0
Contact: cdr-data61@csiro.au
Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.response_banking_product_by_id import (  # noqa: E501
    ResponseBankingProductById,
)
from swagger_client.rest import ApiException


class TestResponseBankingProductById(unittest.TestCase):
    """ResponseBankingProductById unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseBankingProductById(self):
        """Test ResponseBankingProductById"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.response_banking_product_by_id.ResponseBankingProductById()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
